syntax = "proto3";

message TimestampRequest {}
message TimestampResponse {
  uint64 timestamp = 1;
}

message GetRequest {
  bytes key = 1;
  uint64 start_ts = 2;
}

message GetResponse {
  bytes value = 1;
}

message PrewriteRequest {
  bytes key = 1;
  bytes value = 2;
  uint64 start_ts = 3;
  // Primary key of this transaction; empty means `key` itself is primary.
  bytes primary = 4;
}

message PrewriteResponse {}

message CommitRequest {
  bytes key = 1;
  bytes value = 2;
  uint64 start_ts = 3;
  uint64 commit_ts = 4;
}

message CommitResponse {
  bool ok = 1;
}

message RollbackRequest {
  bytes key = 1;
  uint64 start_ts = 2;
}

message RollbackResponse {}

